Repository neokd/NeoGPT, pull requests merged in 2024-02, with the labels that each got.

#162 Add "/history" in magic_commands.py
  neogpt/utils/magic_commands.py
Labels: medium, JWOC

#167 Refactor notify function to use plyer library for desktop notifications
  docs/assets/icon.ico
  neogpt/utils/notify.py
Labels: hard, JWOC

#168 Added documentation in card format for llms in introduction.mdx
  docs/language-models/introduction.mdx
Labels: medium, JWOC

#169 Add /save command to save chat history
  neogpt/utils/magic_commands.py
Labels: medium, JWOC

#171 Add '/copy' command to copy last NeoGPT response to clipboard
  neogpt/utils/magic_commands.py
Labels: hard, JWOC

#174 Add `/undo` command to remove last response from chat history
  neogpt/utils/magic_commands.py
Labels: hard, JWOC

#178 Add /redo command to resend last human input
  neogpt/utils/magic_commands.py
Labels: medium, JWOC

#179 Add magic commands documentation
  docs/guides/magic-commands.mdx
Labels: medium, JWOC

#183 Add support for loading Gutenberg URLs
  neogpt/builder_helpers/load_web.py
  neogpt/config.py
Labels: medium, JWOC

#184 Add new command line arguments for temperature, max tokens, and context windows in main.py
  main.py
Labels: medium, JWOC

#186 Add method to calculate TogetherAI cost based on number of tokens generated
  neogpt/callback_handler.py
Labels: medium, JWOC

#191 Update togetherai model costs and max-budget flag
  main.py
  neogpt/callback_handler.py
Labels: medium, JWOC

#192 Saves chat history to `conversations` directory
  neogpt/callback_handler.py
  neogpt/utils/magic_commands.py
Labels: medium, JWOC

#194 Add token counting functionality to magic_commands.py
  neogpt/utils/magic_commands.py
Labels: easy, JWOC

#196 Add support for reading Word, Excel, and PowerPoint files
  neogpt/utils/read_file.py
Labels: medium, JWOC

#200 Fix regex pattern in read_file.py
  neogpt/utils/read_file.py
Labels: easy, JWOC

#202 Implementing the export config functionality properly
  neogpt/config.py
  neogpt/utils/magic_commands.py
Labels: medium, JWOC

#206 Add load_conversations() and code parameter to writing_assistant function
  neogpt/utils/writer_assistant.py
Labels: medium, JWOC

#208 Custom exit on ctrl+c
  main.py
Labels: easy, JWOC
